//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int FlightTypeID { get; set; }
        public int DepartureFlightID { get; set; }
        public Nullable<int> ArrivalFlightID { get; set; }
        public int NumOfAdults { get; set; }
        public Nullable<int> NumOfChildren { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual FlightInfo FlightInfo { get; set; }
        public virtual FlightInfo FlightInfo1 { get; set; }
        public virtual FlightType FlightType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
